sudo: false

language: node_js

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

addons:
  code_climate:
    repo_token: b96c8e14d13e6e0eac109776042700ebba5cddd019d9031fc476d8110842920f

before_script:
  - node sleep.js

after_script:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
