sudo: false

language: node_js

node_js:
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

addons:
  code_climate:
    repo_token: 3cdde9b8d06b7f0be9658c00e71e16218cf21279c007806f111e6add1956b450

after_script:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
